### ISSUE TITLE
Kaleidoscope-Focus link broken

### ISSUE THREAD

**Issue by micahbf** [algernon/kaleidoscope.el#3]
Hello!

I noticed the link to Kaleidoscope-Focus on the README is broken. Is this still available anywhere?

Thank you!

**Comment by algernon** [comment]
The links bit-rotted a bit, sorry!

The new URL for the plugin documentation is https://kaleidoscope.readthedocs.io/en/latest/plugins/Kaleidoscope-FocusSerial.html

I'll update the README at some point, but PRs to do that would be most appreciated. O:)
